# Numpy: Package for Multidimensional array
## Vector(1d)
### Matrix(2d or 1d)

### Create an array

In [2]:
import numpy as np ## Shift+Enter

In [3]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [4]:
arr=np.array([6,7,9])
arr

array([6, 7, 9])

In [9]:
list_of_lists=[1,2,3],[4,5,6],[7,8,9]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.arange(1,49)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [23]:
np.arange(10,98,8)

array([10, 18, 26, 34, 42, 50, 58, 66, 74, 82, 90])

In [24]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [26]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [31]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [36]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [40]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [47]:
np.random.rand(2,4)


array([[0.11610817, 0.63374109, 0.55361133, 0.84516281],
       [0.75730255, 0.21913224, 0.86971892, 0.57178113]])

In [48]:
np.random.randn(2,4)

array([[ 1.4959871 ,  1.15317395, -1.80525021,  0.28759361],
       [-1.79695604,  0.19364124, -0.79511342, -0.50051642]])

In [55]:
np.random.randint(1,5,4)

array([4, 1, 2, 1])

In [56]:
sample_array=np.arange(2,20)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [57]:
rand_array=np.random.randint(0,10,5)
rand_array

array([8, 7, 3, 2, 9])

In [58]:
sample_array.min()

2

In [59]:
sample_array.argmin()

0

In [60]:
rand_array.argmin()

3

In [61]:
rand_array.max()

9

In [62]:
rand_array.argmax()

4

In [63]:
sample_array.argmax()

17

In [64]:
sample_array.dtype

dtype('int32')

In [65]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
a=np.random.rand(2,3)
a

array([[0.47330953, 0.0210835 , 0.92212735],
       [0.14898223, 0.31150127, 0.67304522]])

In [67]:
a.T


array([[0.47330953, 0.14898223],
       [0.0210835 , 0.31150127],
       [0.92212735, 0.67304522]])

In [68]:
sample_array=np.arange(10,28)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [71]:
sample_array=sample_array.reshape(9,2)
sample_array

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27]])

In [ ]:
sample_array=sample_array.reshape(3,4)
sample_array

In [72]:
sample_array[3]=100
sample_array

array([[ 10,  11],
       [ 12,  13],
       [ 14,  15],
       [100, 100],
       [ 18,  19],
       [ 20,  21],
       [ 22,  23],
       [ 24,  25],
       [ 26,  27]])

In [73]:
sample_array=np.arange(10,100)
sample_array


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [75]:
sample_array[0:5]

array([10, 11, 12, 13, 14])

In [76]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [77]:
sample_array[1:5]=1001
sample_array

array([  10, 1001, 1001, 1001, 1001,   15,   16,   17,   18,   19,   20,
         21,   22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
         32,   33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
         43,   44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
         54,   55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
         65,   66,   67,   68,   69,   70,   71,   72,   73,   74,   75,
         76,   77,   78,   79,   80,   81,   82,   83,   84,   85,   86,
         87,   88,   89,   90,   91,   92,   93,   94,   95,   96,   97,
         98,   99])

In [ ]:
### Recap

In [ ]:
### Code to import Numpy?
### Create an array of 10 zeros with integer datatype
### Create normal distribution of shape 2x 5
### Create unit vector of float data type with shape 3x7
### Identity matrix of 10x10
### O/p:5,10,15,20,25

In [1]:
import numpy as np

In [7]:
array=np.zeros(10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
array=np.zeros(10,dtype=int)
print(array)


[0 0 0 0 0 0 0 0 0 0]


In [9]:
np.zeros((6),dtype=int)


array([0, 0, 0, 0, 0, 0])

In [11]:
np.random.randn(2,5)


array([[ 0.08776049, -0.77705333,  1.45490788, -1.08001214, -0.39019188],
       [ 0.03475783, -0.40471693, -0.79093829,  0.49649642, -1.53114875]])

In [14]:
np.ones((3,7))


array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [15]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
var=[5,10,15,20,25]
np.array(var)


array([ 5, 10, 15, 20, 25])

In [18]:
np.arange(5,30,5)


array([ 5, 10, 15, 20, 25])

In [21]:
np.linspace(5,25,5)


array([ 5., 10., 15., 20., 25.])

### Two-Dimensional array

In [ ]:
import numpy as np

In [26]:
sample_matrix=np.array(([24,13,2,15],[15,54,65,23],[56,76,24,7]))
sample_matrix

array([[24, 13,  2, 15],
       [15, 54, 65, 23],
       [56, 76, 24,  7]])

In [42]:
sample_matrix[2:,1:3]


array([[76, 24]])

In [34]:
sample_matrix[0][2]

2

In [ ]:
sample_matrix[1][3]

In [36]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [39]:
sample_matrix[1:2,2:3]

array([[65]])

In [40]:
sample_matrix[1:,2:]

array([[65, 23],
       [24,  7]])

In [41]:
sample_matrix[2]

array([56, 76, 24,  7])

In [51]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [52]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [53]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [54]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [55]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [56]:
np.max(sample_array)

30

In [57]:
np.min(sample_array)

1

In [58]:
np.argmax(sample_array)

29

In [59]:
np.argmin(sample_array)

0

In [60]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [61]:
np.std(sample_array)

8.65544144839919

In [62]:
np.var(sample_array)


74.91666666666667

In [63]:
np.mean(sample_array)

15.5

In [64]:
array=np.random.randn(3,4) ### normal distribution
array

array([[-1.7585666 , -0.38772452, -1.43193349, -0.91225442],
       [ 1.31261677, -0.59635767,  1.42140187,  1.1705793 ],
       [ 0.33511699, -1.97393627, -0.94054738, -0.14224639]])

In [65]:
np.round(array,decimals=3)

array([[-1.759, -0.388, -1.432, -0.912],
       [ 1.313, -0.596,  1.421,  1.171],
       [ 0.335, -1.974, -0.941, -0.142]])

In [68]:
fruits=np.array(['apple','orange','mango','apple','orange'])
np.unique(fruits)

array(['apple', 'mango', 'orange'], dtype='<U6')

### Pandas

In [69]:
import pandas as pd

In [ ]:
import numpy as np

### Pandas dataframe and indexing

In [70]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [71]:
sports1['basketball']


3

In [72]:
sports1['golf']

4

In [77]:
sports2=pd.Series([11,13,12,4],index=['cricket','football','baseball','golf'],)
sports2


cricket     11
football    13
baseball    12
golf         4
dtype: int64

In [74]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football      15.0
golf           8.0
dtype: float64

In [80]:

df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.521688  0.837147  0.439066  0.171235  0.034089
B  0.786243  0.301358  0.386291  0.734305  0.576629
C  0.961050  0.046831  0.023491  0.673145  0.566720
D  0.507127  0.520022  0.391311  0.225279  0.029966
E  0.521888  0.939461  0.493535  0.591665  0.519679
F  0.910917  0.439377  0.478556  0.064612  0.146560
G  0.797366  0.871183  0.676623  0.159012  0.987601
H  0.805814  0.706859  0.359737  0.780964  0.179885

In [82]:
df1['Score2']

A    0.837147
B    0.301358
C    0.046831
D    0.520022
E    0.939461
F    0.439377
G    0.871183
H    0.706859
Name: Score2, dtype: float64

In [85]:
df1[['Score1','Score2','Score3']]

Score1    Score2    Score3
A  0.521688  0.837147  0.439066
B  0.786243  0.301358  0.386291
C  0.961050  0.046831  0.023491
D  0.507127  0.520022  0.391311
E  0.521888  0.939461  0.493535
F  0.910917  0.439377  0.478556
G  0.797366  0.871183  0.676623
H  0.805814  0.706859  0.359737

In [ ]:
df1[['Score4','Score2','Score5']]

In [86]:
df1['Score6']=df1['Score1']+df1['Score2']
df1


Score1    Score2    Score3    Score4    Score5    Score6
A  0.521688  0.837147  0.439066  0.171235  0.034089  1.358836
B  0.786243  0.301358  0.386291  0.734305  0.576629  1.087601
C  0.961050  0.046831  0.023491  0.673145  0.566720  1.007880
D  0.507127  0.520022  0.391311  0.225279  0.029966  1.027149
E  0.521888  0.939461  0.493535  0.591665  0.519679  1.461349
F  0.910917  0.439377  0.478556  0.064612  0.146560  1.350294
G  0.797366  0.871183  0.676623  0.159012  0.987601  1.668549
H  0.805814  0.706859  0.359737  0.780964  0.179885  1.512673

In [89]:
df1.drop("Score3",axis=1)

Score1    Score2    Score4    Score5    Score6
A  0.521688  0.837147  0.171235  0.034089  1.358836
B  0.786243  0.301358  0.734305  0.576629  1.087601
C  0.961050  0.046831  0.673145  0.566720  1.007880
D  0.507127  0.520022  0.225279  0.029966  1.027149
E  0.521888  0.939461  0.591665  0.519679  1.461349
F  0.910917  0.439377  0.064612  0.146560  1.350294
G  0.797366  0.871183  0.159012  0.987601  1.668549
H  0.805814  0.706859  0.780964  0.179885  1.512673

In [87]:
df1.drop('E')

Score1    Score2    Score3    Score4    Score5    Score6
A  0.521688  0.837147  0.439066  0.171235  0.034089  1.358836
B  0.786243  0.301358  0.386291  0.734305  0.576629  1.087601
C  0.961050  0.046831  0.023491  0.673145  0.566720  1.007880
D  0.507127  0.520022  0.391311  0.225279  0.029966  1.027149
F  0.910917  0.439377  0.478556  0.064612  0.146560  1.350294
G  0.797366  0.871183  0.676623  0.159012  0.987601  1.668549
H  0.805814  0.706859  0.359737  0.780964  0.179885  1.512673

In [91]:
df1.drop('Score1',axis=1) 


Score2    Score3    Score4    Score5    Score6
A  0.837147  0.439066  0.171235  0.034089  1.358836
B  0.301358  0.386291  0.734305  0.576629  1.087601
C  0.046831  0.023491  0.673145  0.566720  1.007880
D  0.520022  0.391311  0.225279  0.029966  1.027149
E  0.939461  0.493535  0.591665  0.519679  1.461349
F  0.439377  0.478556  0.064612  0.146560  1.350294
G  0.871183  0.676623  0.159012  0.987601  1.668549
H  0.706859  0.359737  0.780964  0.179885  1.512673

In [92]:
df1.drop("A",axis=0)


Score1    Score2    Score3    Score4    Score5    Score6
B  0.786243  0.301358  0.386291  0.734305  0.576629  1.087601
C  0.961050  0.046831  0.023491  0.673145  0.566720  1.007880
D  0.507127  0.520022  0.391311  0.225279  0.029966  1.027149
E  0.521888  0.939461  0.493535  0.591665  0.519679  1.461349
F  0.910917  0.439377  0.478556  0.064612  0.146560  1.350294
G  0.797366  0.871183  0.676623  0.159012  0.987601  1.668549
H  0.805814  0.706859  0.359737  0.780964  0.179885  1.512673

In [93]:
df1.drop(["Score1","Score2"],axis=1)


Score3    Score4    Score5    Score6
A  0.439066  0.171235  0.034089  1.358836
B  0.386291  0.734305  0.576629  1.087601
C  0.023491  0.673145  0.566720  1.007880
D  0.391311  0.225279  0.029966  1.027149
E  0.493535  0.591665  0.519679  1.461349
F  0.478556  0.064612  0.146560  1.350294
G  0.676623  0.159012  0.987601  1.668549
H  0.359737  0.780964  0.179885  1.512673

In [105]:
df2={'ID':[101,102,103,107,176],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavin      87
4  176  Lally     123

In [ ]:
df.drop('ID',axis=1)

In [ ]:
df.drop(3)

In [ ]:
df[['Name','Profit']]

In [ ]:
df[['Name','ID']]

In [ ]:
df=pd.read_csv("innercity.csv")

In [ ]:
df.head()

In [ ]:
### Assessment

1) Create a null vector of size 10
2) Create a null vector of size 10 but the fifth value should be one
3) Create a vector with values ranging from 10 to 65
4) Reverse the above vector
5) Create a 3x3 matrix with values ranging from 0 to 8


In [ ]:
import numpy as np
np.zeros(10)

In [ ]:
a=np.zeros(10)
a[4]=1
a

In [ ]:
z=np.arange(10,66)
z

In [ ]:
z=np.arange(65,9,-1)
z

In [ ]:
x =  np.arange(0,9).reshape(3,3)
print(x)


In [113]:
import numpy as np
import pandas as pd


In [116]:
df=pd.read_csv("Automobile.csv")

In [115]:
df.head()

symboling  normalized_losses         make fuel_type aspiration  \
0          3                168  alfa-romero       gas        std   
1          3                168  alfa-romero       gas        std   
2          1                168  alfa-romero       gas        std   
3          2                164         audi       gas        std   
4          2                164         audi       gas        std   

  number_of_doors   body_style drive_wheels engine_location  wheel_base  ...  \
0             two  convertible          rwd           front        88.6  ...   
1             two  convertible          rwd           front        88.6  ...   
2             two    hatchback          rwd           front        94.5  ...   
3            four        sedan          fwd           front        99.8  ...   
4            four        sedan          4wd           front        99.4  ...   

   engine_size  fuel_system  bore  stroke compression_ratio horsepower  \
0          130         mpfi  3.47    2.68               9.0        111   
1          130         mpfi  3.47    2.68               9.0        111   
2          152         mpfi  2.68    3.47               9.0        154   
3          109         mpfi  3.19    3.40              10.0        102   
4          136         mpfi  3.19    3.40               8.0        115   

   peak_rpm city_mpg  highway_mpg  price  
0      5000       21           27  13495  
1      5000       21           27  16500  
2      5000       19           26  16500  
3      5500       24           30  13950  
4      5500       18           22  17450  

[5 rows x 26 columns]

In [128]:
df

symboling  normalized_losses         make fuel_type aspiration  \
0            3                168  alfa-romero       gas        std   
1            3                168  alfa-romero       gas        std   
2            1                168  alfa-romero       gas        std   
3            2                164         audi       gas        std   
4            2                164         audi       gas        std   
..         ...                ...          ...       ...        ...   
196         -1                 95        volvo       gas        std   
197         -1                 95        volvo       gas      turbo   
198         -1                 95        volvo       gas        std   
199         -1                 95        volvo    diesel      turbo   
200         -1                 95        volvo       gas      turbo   

    number_of_doors   body_style drive_wheels engine_location  wheel_base  \
0               two  convertible          rwd           front        88.6   
1               two  convertible          rwd           front        88.6   
2               two    hatchback          rwd           front        94.5   
3              four        sedan          fwd           front        99.8   
4              four        sedan          4wd           front        99.4   
..              ...          ...          ...             ...         ...   
196            four        sedan          rwd           front       109.1   
197            four        sedan          rwd           front       109.1   
198            four        sedan          rwd           front       109.1   
199            four        sedan          rwd           front       109.1   
200            four        sedan          rwd           front       109.1   

     ...  engine_size  fuel_system  bore  stroke compression_ratio horsepower  \
0    ...          130         mpfi  3.47    2.68               9.0        111   
1    ...          130         mpfi  3.47    2.68               9.0        111   
2    ...          152         mpfi  2.68    3.47               9.0        154   
3    ...          109         mpfi  3.19    3.40              10.0        102   
4    ...          136         mpfi  3.19    3.40               8.0        115   
..   ...          ...          ...   ...     ...               ...        ...   
196  ...          141         mpfi  3.78    3.15               9.5        114   
197  ...          141         mpfi  3.78    3.15               8.7        160   
198  ...          173         mpfi  3.58    2.87               8.8        134   
199  ...          145          idi  3.01    3.40              23.0        106   
200  ...          141         mpfi  3.78    3.15               9.5        114   

     peak_rpm city_mpg  highway_mpg  price  
0        5000       21           27  13495  
1        5000       21           27  16500  
2        5000       19           26  16500  
3        5500       24           30  13950  
4        5500       18           22  17450  
..        ...      ...          ...    ...  
196      5400       23           28  16845  
197      5300       19           25  19045  
198      5500       18           23  21485  
199      4800       26           27  22470  
200      5400       19           25  22625  

[201 rows x 26 columns]

In [117]:
df.tail()

symboling  normalized_losses   make fuel_type aspiration number_of_doors  \
196         -1                 95  volvo       gas        std            four   
197         -1                 95  volvo       gas      turbo            four   
198         -1                 95  volvo       gas        std            four   
199         -1                 95  volvo    diesel      turbo            four   
200         -1                 95  volvo       gas      turbo            four   

    body_style drive_wheels engine_location  wheel_base  ...  engine_size  \
196      sedan          rwd           front       109.1  ...          141   
197      sedan          rwd           front       109.1  ...          141   
198      sedan          rwd           front       109.1  ...          173   
199      sedan          rwd           front       109.1  ...          145   
200      sedan          rwd           front       109.1  ...          141   

     fuel_system  bore  stroke compression_ratio horsepower  peak_rpm  \
196         mpfi  3.78    3.15               9.5        114      5400   
197         mpfi  3.78    3.15               8.7        160      5300   
198         mpfi  3.58    2.87               8.8        134      5500   
199          idi  3.01    3.40              23.0        106      4800   
200         mpfi  3.78    3.15               9.5        114      5400   

    city_mpg  highway_mpg  price  
196       23           28  16845  
197       19           25  19045  
198       18           23  21485  
199       26           27  22470  
200       19           25  22625  

[5 rows x 26 columns]

In [120]:
df.sample()

symboling  normalized_losses    make fuel_type aspiration  \
176         -1                 90  toyota       gas        std   

    number_of_doors body_style drive_wheels engine_location  wheel_base  ...  \
176            four      sedan          rwd           front       104.5  ...   

     engine_size  fuel_system  bore  stroke compression_ratio horsepower  \
176          171         mpfi  3.27    3.35               9.2        156   

     peak_rpm city_mpg  highway_mpg  price  
176      5200       20           24  15690  

[1 rows x 26 columns]

In [122]:
df.sample(10)

symboling  normalized_losses        make fuel_type aspiration  \
23           1                148       dodge       gas        std   
168          2                134      toyota       gas        std   
8            1                158        audi       gas      turbo   
73           2                161  mitsubishi       gas        std   
172         -1                 65      toyota       gas        std   
53           3                150       mazda       gas        std   
37           0                106       honda       gas        std   
111          0                161      peugot    diesel      turbo   
110          0                161      peugot       gas        std   
41           1                107       honda       gas        std   

    number_of_doors   body_style drive_wheels engine_location  wheel_base  \
23             four    hatchback          fwd           front        93.7   
168             two  convertible          rwd           front        98.4   
8              four        sedan          fwd           front       105.8   
73              two    hatchback          fwd           front        93.7   
172            four        sedan          fwd           front       102.4   
53              two    hatchback          rwd           front        95.3   
37              two    hatchback          fwd           front        96.5   
111            four        wagon          rwd           front       114.2   
110            four        wagon          rwd           front       114.2   
41              two        sedan          fwd           front        96.5   

     ...  engine_size  fuel_system  bore  stroke compression_ratio horsepower  \
23   ...           90         2bbl  2.97    3.23               9.4         68   
168  ...          146         mpfi  3.62    3.50               9.3        116   
8    ...          131         mpfi  3.13    3.40               8.3        140   
73   ...           92         2bbl  2.97    3.23               9.4         68   
172  ...          122         mpfi  3.31    3.54               8.7         92   
53   ...           70         4bbl  3.28    3.50               9.4        101   
37   ...          110         1bbl  3.15    3.58               9.0         86   
111  ...          152          idi  3.70    3.52              21.0         95   
110  ...          120         mpfi  3.46    2.19               8.4         95   
41   ...          110         2bbl  3.15    3.58               9.1        100   

     peak_rpm city_mpg  highway_mpg  price  
23       5500       31           38   6229  
168      4800       24           30  17669  
8        5500       17           20  23875  
73       5500       37           41   5389  
172      4200       27           32  10898  
53       6000       17           23  11845  
37       5800       27           33   9095  
111      4150       25           25  17075  
110      5000       19           24  16695  
41       5500       25           31  10345  

[10 rows x 26 columns]

In [123]:
df.shape

(201, 26)

In [124]:
df.columns

Index(['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration',
       'number_of_doors', 'body_style', 'drive_wheels', 'engine_location',
       'wheel_base', 'length', 'width', 'height', 'curb_weight', 'engine_type',
       'number_of_cylinders', 'engine_size', 'fuel_system', 'bore', 'stroke',
       'compression_ratio', 'horsepower', 'peak_rpm', 'city_mpg',
       'highway_mpg', 'price'],
      dtype='object')

In [125]:
df.dtypes

symboling                int64
normalized_losses        int64
make                    object
fuel_type               object
aspiration              object
number_of_doors         object
body_style              object
drive_wheels            object
engine_location         object
wheel_base             float64
length                 float64
width                  float64
height                 float64
curb_weight              int64
engine_type             object
number_of_cylinders     object
engine_size              int64
fuel_system             object
bore                   float64
stroke                 float64
compression_ratio      float64
horsepower               int64
peak_rpm                 int64
city_mpg                 int64
highway_mpg              int64
price                    int64
dtype: object

In [126]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   symboling            201 non-null    int64  
 1   normalized_losses    201 non-null    int64  
 2   make                 201 non-null    object 
 3   fuel_type            201 non-null    object 
 4   aspiration           201 non-null    object 
 5   number_of_doors      201 non-null    object 
 6   body_style           201 non-null    object 
 7   drive_wheels         201 non-null    object 
 8   engine_location      201 non-null    object 
 9   wheel_base           201 non-null    float64
 10  length               201 non-null    float64
 11  width                201 non-null    float64
 12  height               201 non-null    float64
 13  curb_weight          201 non-null    int64  
 14  engine_type          201 non-null    object 
 15  number_of_cylinders  201 non-null    obj

In [96]:
Roll_no=pd.Series([1,2,3,4,5,6,7,8],index=["Madhu","Dillisree","Philip","Preetham","Rupesh","Sesha","Tanuja","Vasanth"])
                

In [97]:
Roll_no

Madhu        1
Dillisree    2
Philip       3
Preetham     4
Rupesh       5
Sesha        6
Tanuja       7
Vasanth      8
dtype: int64

In [99]:
Roll_no["Sesha"]

6

In [ ]:
df2={'ID':[101,102,103,107,176],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

In [108]:
df={'Numbers':[1,2,3,4,5,6,7,8],'Names':["Madhu","Dillisree","Philip","Preetham","Rupesh","Sesha","Tanuja","Vasanth"]}
Roll_no=pd.DataFrame(df)
Roll_no               

Numbers      Names
0        1      Madhu
1        2  Dillisree
2        3     Philip
3        4   Preetham
4        5     Rupesh
5        6      Sesha
6        7     Tanuja
7        8    Vasanth

In [110]:
Roll_no.drop(3)

Numbers      Names
0        1      Madhu
1        2  Dillisree
2        3     Philip
4        5     Rupesh
5        6      Sesha
6        7     Tanuja
7        8    Vasanth

In [112]:
Roll_no.drop("Numbers",axis=1)

Names
0      Madhu
1  Dillisree
2     Philip
3   Preetham
4     Rupesh
5      Sesha
6     Tanuja
7    Vasanth